<?php

use App\Enums\Programname;

return [
    Programname::Meyer => '<h5>Entering 7th, 8th or 9th grades</h5><p>In the Junior High Program or, "Meyer," junior highers live together in a cabin with their hardworking counselors who create a safe place for sharing, learning their own boundaries and building a fantastic community. Our young teens participate in team-building initiatives, mystery solving, pun-offs, games, dancing, and workshops focused on creating change and growth, personally and community wide. All Meyer activities are designed to support emotional and spiritual growth, and empower junior high youth. We are also sure to have plenty of fun, like it&apos;s a vacation or something! For more information, use the Contact Us form above.</p>',
    Programname::Cratty => '<p>Our experienced staff teams up with YMCA staff to facilitate teambuilding games, arts and crafts, outdoor activities, wall climbing, archery, swimming, hiking, boating, religious education, ranch activities and much more. School age children are divided into groups based on their age at camp: 6 &amp; 7-year-olds; 8 &amp; 9-year-olds; and 10+ years. Placement is based on age restriction for the YMCA activities in which we participate. Each group will engage in a wide range of activities that are suited to their age, with an emphasis on combining traditional camp fun with UU themes. Different learning styles and personalities of children are considered so no one feels left out or bored. Lifelong camp experiences start here! Use the Contact Us form above for questions. Please contact us if your child needs special accommodations to fully participate in the program.</p><p><br></p><p></p>',
    Programname::Burt => '<h5>Entering 10th, 11th or 12th grades</h5><p>In our Sr. High program, which we call "Burt," we create a community where we love and support everyone no matter what, where we become courageous and responsible, discover ourselves, make life-long friends, and have a ton of fun. We do this through required and optional activities such as daily small groups, nightly youth-led worship, a ropes course, and much more. "Burtoids" live together in a Camp Lakewood Cabin with the help of a caring and dedicated staff. Each year we delve into how UU principles can guide us to make a positive difference in the world around us. For more information, use the Contact Us form above.</p>',
    Programname::Lumens => '<p>Our attentive, caring nursery staff provides a safe and fun environment for our infants. Is your child past naptime? No problem: 4 &amp; 5-year-olds enjoy crafts and a wide range of indoor and outdoor fun and educational activities. For more information, use the Contact Us form above for questions.<br></p>',
    Programname::Adult => '<p>Couples and singles, with and without children, are welcome to attend MUUSA. After morning celebration, adults can enjoy a variety of workshop and recreational activities while children are in their programs. Workshops are held M-F, anywhere from 1 to 5 days, and last just under 2 hours. Choose from spiritual topics, crafts, music, dance or outdoor activities. Workshops run just under 2 hours and range from 1 day to 5 days. MUUSA and Trout Lodge provide other informal adult programming as well. For more information, use the Contact Us form above.</p>',
    Programname::YoungAdult => '<p>A special welcome to and from the MUUSA Young Adult program! We are an awesome collection of UUs, ages 18-35, who plan our own late-night worships, go for paintball, lead workshops, and hang out! We have YA-specific cabins in Camp Lakewood (priority for YAs under 21), but our community is all over the camp!</p><p>For more information about the YA program, or if you have an idea you would like to share, use the Contact Us form above.</p>'
];
